### PR TITLE
Implement faster chebyshev evaluation

### PR DESCRIPTION
**Pull request by mzbush**
Using Python libraries is generally faster

### CODE REVIEW

**Comment by mphoward** [comment]
Thanks! Could you please report timings for evaluating the `ChebyshevFirstKind` before and after this PR?

You can use the built-in `timeit` module to do this:
https://docs.python.org/3/library/timeit.html

**Comment by mzbush** [comment]
When running 1000 random calls for n = 0 to 99 each, it took about 4.17 seconds before. With this fix, it takes about 0.33 seconds.

**Comment by mphoward** [comment]
Thanks, that is great! To make it easier for me to understand, can you run just `n=2, 4, 8, 16, 32` for one point (say `x=0.5`), and report the `timeit` for 1000 or maybe even 10000 calls as a table here in the PR with three columns: `n`, old method, new method.

How to make tables of GitHub Markdown:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

**Comment by mzbush** [comment]
Times in seconds after running 100,000 times with x = 0.5
 | n| Before  | After
|----|----------|----------|
| 2|0.143598 |0.119076|
| 4|0.201770 |0.120749|
| 8|0.333639 |0.121037|
|16|0.656484 |0.123332|
|32|1.482065 |0.131643|

**Comment by mphoward** [comment]
Great! This is what I thought could happen. The cost of evaluating the polynomials increases greatly with n for the old method, but is nearly constant for the new method. This will be a huge improvement for higher accuracy surrogates that contain higher order polynomials. Good find and good work!

**Review by mphoward — APPROVED** [review]
This is a drop-in replacement. If you have verified all existing tests pass, this is ready to merge.

**Pull request merged**
